name: saga-build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - src/**
  pull_request:
    branches: [ main ]
    paths: 
      - src/**

env:
  CONFIGURATION: Release
  DOTNET_VERSION: 6.0.x
  WORKING_DIRECTORY: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: dotnet restore

    - name: Build
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: dotnet test --no-restore --verbosity normal
